---

- hosts: all
  become: true
  tasks:
  - name: update and upgrade the servers
    apt:
      update_cache: yes
      upgrade: yes

  - name: Install Apache2
    tags: apache, apache2, ubuntu
    apt:
      name:
        - apache2
      state: present

  - name: Set timezone to Africa/Lagos
    tags: time
    timezone:
      name: Africa/Lagos

  - name: Print hostname on server
    tags: hostname
    shell: echo "<h1>This is my server name $(hostname -f)</h1>" > /var/www/html/index.html

  - name: Restart apache2
    tags: Restart
    service:
      name: apache2
      state: restarted
